### ISSUE TITLE
v2.2.1: tls-alpn-01 challenge seems to be broken

### ISSUE THREAD

**Issue by shred** [letsencrypt/pebble#264] opened 2019-08-04 07:51 UTC
In Pebble v2.2.1, the `tls-alpn-01` challenge seems to ignore the `-dnsserver` option.

For my integration tests, I use `-dnsserver` to point Pebble to a challtestsrv docker instance. This worked in previous Pebble versions, but in v2.2.1, the `tls-alpn-01` challenge fails with the error message `Failed to connect to example.com:5001 for the tls-alpn-01 challenge`.

I've tested Pebble against an old, self-made test server, and could reproduce the error. There was no server log record for a tls-alpn request, so I guess that Pebble is actually connecting to `example.com` instead of the challtestsrv docker instance.

All other challenges work fine with Pebble v2.2.1.

**Comment by felixfontein** [comment] 2019-08-04 09:51
Which version was the last one you were able to use successfully? In 2.2.1, #255 has been merged which fixes `--dnsserver` for Windows. Maybe it's related to that change?

Looking at the change, it's maybe caused because `validateTLSALPN01` was not updated to use the new dialer, and the old method (modifying Go's default resolver) was removed. @adferrand can you take a look since you probably know your PR best?

**Comment by shred** [comment] 2019-08-04 10:32
I run an automated integration test every Sunday. The last successful run was with Pebble docker image digest 107addd3[...], which is v2.1.0.

**Comment by felixfontein** [comment] 2019-08-04 10:41
In that case it really looks like it is related to #255, since nothing else changed w.r.t. DNS resolving, and TLS-ALPN-01 was not touched at all.

**Comment by adferrand** [comment] 2019-08-04 19:11
Indeed @felixfontein, @shred, it is very likely that my PR broke TLS-ALPN-01 here ...

I made an attempt to fix it, and would like to submit a PR right now. However, I would need a test to check that my fix is effectively resolving the situation. @shred, could you give me the integration test you are using to test TLS-ALPN-01? Alternatively, you can also compile a local Pebble instance against https://github.com/adferrand/pebble/tree/fix-tlsalpn01-dns, and check that your test is working again.

Very sorry for the trouble ...

**Comment by adferrand** [comment] 2019-08-04 19:33
Nevermind. I found the integration tests in Acme4j, and was able to reproduce the failure.

I tested against my branch `fix-tlsalpn01-dns` and it made all tests pass.

I open a PR right now.

**Closed** 2019-08-05 16:10 UTC

**Comment by cpu** [comment] 2019-08-05 16:11
Thanks everyone. I appreciate the community effort that caught the bug and got it fixed right away :-)

**Comment by cpu** [comment] 2019-08-05 16:49
I tagged a point release with the fix: https://github.com/letsencrypt/pebble/releases/tag/v2.2.2

Lucky v:two:.:two:.:two:
